# Generated by Django 5.2.8 on 2025-11-20 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei_serial', models.CharField(max_length=50, unique=True, verbose_name='IMEI / Serial Number')),
                ('mint_date', models.DateTimeField(auto_now_add=True)),
                ('wipe_standard', models.CharField(max_length=100)),
                ('is_certified', models.BooleanField(default=False)),
                ('chain_hash', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('event_data', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core_passport.digitalpassport')),
            ],
        ),
    ]
